using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DragonGate;
using UnityEditor;
using UnityEngine;

/// <summary>
/// BlackboardAsset의 키 목록을 읽어 string 상수 파일을 생성한다.
/// 노드에서 GetKey&lt;T&gt;(StaffBBKeys.IsHungry) 형태로 오타 없이 키를 참조할 수 있다.
/// </summary>
public static class BlackboardKeyCodeGenerator
{
    public static void Generate(BlackboardAsset asset)
    {
        if (string.IsNullOrEmpty(asset.generatedKeysClassName))
        {
            Debug.LogError("[BlackboardKeyCodeGenerator] Generated Class Name이 비어 있습니다.");
            return;
        }
        if (string.IsNullOrEmpty(asset.generatedKeysFilePath))
        {
            Debug.LogError("[BlackboardKeyCodeGenerator] Generated File Path가 비어 있습니다.");
            return;
        }

        var assetPath = AssetDatabase.GetAssetPath(asset);
        var sb = new StringBuilder();

        sb.AppendLine("// AUTO-GENERATED by Blackboard Asset — 직접 편집 금지");
        sb.AppendLine($"// Source: {assetPath}");
        sb.AppendLine();
        sb.AppendLine($"public static class {asset.generatedKeysClassName}");
        sb.AppendLine("{");

        foreach (var key in asset.keys)
        {
            var typeHint = key.KeyType.ToString().ToLower();
            sb.AppendLine($"    public const string {key.Name} = \"{key.Name}\"; // {typeHint}");
        }

        sb.AppendLine("}");

        var dir = Path.GetDirectoryName(asset.generatedKeysFilePath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(asset.generatedKeysFilePath, sb.ToString(), Encoding.UTF8);
        AssetDatabase.ImportAsset(asset.generatedKeysFilePath);
        Debug.Log($"[BlackboardKeyCodeGenerator] 생성 완료 → {asset.generatedKeysFilePath}");
    }
}