using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using DragonGate;
using UnityEditor;
using UnityEngine;

/// <summary>
/// BTGraphAsset을 읽어 BuildTreeInCode()를 구현하는 partial 클래스 C# 파일을 생성한다.
/// 런타임에 BTGraphAsset 로딩, Factory, Registry가 전혀 필요 없다.
/// </summary>
public static class BTCodeGenerator
{
    public static void Generate(BTGraphAsset asset)
    {
        if (string.IsNullOrEmpty(asset.targetClassName))
        {
            DGDebug.LogError("[BTCodeGenerator] Target Class Name이 비어 있습니다.");
            return;
        }
        if (string.IsNullOrEmpty(asset.generatedFilePath))
        {
            DGDebug.LogError("[BTCodeGenerator] Generated File Path가 비어 있습니다.");
            return;
        }
        if (string.IsNullOrEmpty(asset.rootGuid) || asset.nodes.Count == 0)
        {
            DGDebug.LogError("[BTCodeGenerator] 그래프가 비어 있습니다. 노드를 추가하고 저장하세요.");
            return;
        }

        var code = BuildCode(asset);
        var dir = Path.GetDirectoryName(asset.generatedFilePath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(asset.generatedFilePath, code, System.Text.Encoding.UTF8);
        AssetDatabase.ImportAsset(asset.generatedFilePath);
        Debug.Log($"[BTCodeGenerator] 생성 완료 → {asset.generatedFilePath}");
    }

    private static string BuildCode(BTGraphAsset asset)
    {
        var sb = new StringBuilder();
        var assetPath = AssetDatabase.GetAssetPath(asset);

        sb.AppendLine("// AUTO-GENERATED by BT Graph Editor — 직접 편집 금지");
        sb.AppendLine($"// Source: {assetPath}");
        sb.AppendLine($"// Target: {asset.targetClassName}");
        sb.AppendLine();
        sb.AppendLine("using DragonGate;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {asset.targetClassName} : BTBrain");
        sb.AppendLine("{");
        sb.AppendLine("    protected override DragonGate.BTNode BuildTreeInCode()");
        sb.AppendLine("    {");

        // guid → BTNodeData 맵
        var nodeMap = new Dictionary<string, BTNodeData>();
        foreach (var n in asset.nodes)
            nodeMap[n.guid] = n;

        // BFS로 순서 결정 (루트 → 자식)
        var order = BfsOrder(asset.rootGuid, nodeMap);

        // 변수명 할당: node_0, node_1, ...
        var varName = new Dictionary<string, string>();
        for (int i = 0; i < order.Count; i++)
            varName[order[i]] = $"node_{i}";

        // 변수 선언
        foreach (var guid in order)
        {
            if (!nodeMap.TryGetValue(guid, out var data)) continue;
            sb.AppendLine($"        var {varName[guid]} = {InstantiationCode(data)};");
        }

        sb.AppendLine();

        // 부모-자식 연결
        foreach (var guid in order)
        {
            if (!nodeMap.TryGetValue(guid, out var data)) continue;
            if (data.childrenGuids.Count == 0) continue;

            var type = Type.GetType(data.typeName);
            var parent = varName[guid];

            if (type != null && typeof(CompositeNode).IsAssignableFrom(type))
            {
                foreach (var childGuid in data.childrenGuids)
                {
                    if (varName.TryGetValue(childGuid, out var child))
                        sb.AppendLine($"        {parent}.AddChild({child});");
                }
            }
            else if (type != null && typeof(DecoratorNode).IsAssignableFrom(type))
            {
                if (varName.TryGetValue(data.childrenGuids[0], out var child))
                    sb.AppendLine($"        {parent}.SetChild({child});");
            }
        }

        sb.AppendLine();
        sb.AppendLine($"        return {varName[asset.rootGuid]};");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ─── BFS ──────────────────────────────────────────────────────────────

    private static List<string> BfsOrder(string rootGuid, Dictionary<string, BTNodeData> nodeMap)
    {
        var order = new List<string>();
        var queue = new Queue<string>();
        var visited = new HashSet<string>();

        queue.Enqueue(rootGuid);
        while (queue.Count > 0)
        {
            var guid = queue.Dequeue();
            if (!visited.Add(guid)) continue;
            order.Add(guid);

            if (nodeMap.TryGetValue(guid, out var data))
                foreach (var child in data.childrenGuids)
                    queue.Enqueue(child);
        }
        return order;
    }

    // ─── 인스턴스 생성 코드 ────────────────────────────────────────────────

    private static string InstantiationCode(BTNodeData data)
    {
        var type = Type.GetType(data.typeName);
        var fullName = type != null ? type.FullName : data.typeName;

        var initializers = ParamInitializers(type, data.paramJson);
        return initializers.Count == 0
            ? $"new {fullName}()"
            : $"new {fullName} {{ {string.Join(", ", initializers)} }}";
    }

    private static List<string> ParamInitializers(Type type, string paramJson)
    {
        var parts = new List<string>();
        if (type == null || string.IsNullOrEmpty(paramJson)) return parts;

        object defaults, restored;
        try
        {
            defaults = Activator.CreateInstance(type);
            restored = Activator.CreateInstance(type);
            JsonUtility.FromJsonOverwrite(paramJson, restored);
        }
        catch { return parts; }

        // public / [SerializeField] 필드 중 기본값과 다른 것만 출력
        var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
        foreach (var field in fields)
        {
            if (!field.IsPublic && field.GetCustomAttribute<SerializeField>() == null) continue;
            if (field.DeclaringType == typeof(BTNode)) continue;

            var def = field.GetValue(defaults);
            var val = field.GetValue(restored);
            if (Equals(def, val)) continue;

            var code = ToLiteral(field.FieldType, val);
            if (code != null)
                parts.Add($"{field.Name} = {code}");
        }
        return parts;
    }

    private static string ToLiteral(Type t, object v)
    {
        if (t == typeof(float))  return $"{(float)v}f";
        if (t == typeof(int))    return $"{(int)v}";
        if (t == typeof(bool))   return (bool)v ? "true" : "false";
        if (t == typeof(string)) return $"\"{v}\"";
        return null;
    }
}